# Generated by Django 3.1.5 on 2021-01-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
