# Generated by Django 3.1.5 on 2021-01-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('weekly_laundry_loads', models.IntegerField()),
                ('daily_bathroom_trips', models.IntegerField()),
                ('weekly_showers', models.IntegerField()),
                ('shower_times', models.IntegerField()),
                ('weekly_baths', models.IntegerField()),
                ('weekly_dishes', models.IntegerField()),
                ('weekly_sprinkler', models.IntegerField()),
                ('swimming_pool', models.BooleanField(default=False)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
