# Generated by Django 3.1.3 on 2021-01-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shower_head_choices',
            field=models.CharField(choices=[('Normal Shower Head', 'Normal Shower Head'), ('Efficient Shower Head', 'Efficient Shower Head')], default='---', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='washer_type_choices',
            field=models.CharField(choices=[('Top Load Washer', 'Top Load Washer'), ('Front Load Washer', 'Front Load Washer')], default='---', max_length=30),
            preserve_default=False,
        ),
    ]
