# Generated by Django 3.1.3 on 2021-01-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210123_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='swimming_pool_choices',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
