# Generated by Django 3.1.3 on 2021-01-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_swimming_pool_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='swimming_pool_choices',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ("I Don't Have A Pool", "I Don't Have A Pool")], max_length=30),
        ),
    ]
