# Generated by Django 3.1.3 on 2021-01-23 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20210123_1508'),
        ('user_profile', '0003_auto_20210123_1632'),
    ]

    operations = [
    ]
